### ISSUE TITLE
DevTools config tab is exposing secrets used in app-config.yaml

### ISSUE THREAD

**Issue by SmajlovicA** [electrolux-oss/infrawallet#128]
Hi team,

I noticed in the DevTools plugin that we show app-config.yaml file configuration (JSON), the first secret is hidden but others are exposed. Maybe I misconfigured something, here is my app-config.yaml configuration:

```yaml
backend:
  infraWallet:
    integrations:
      azure:
        - name: AZURE_SUBSCRIPTION1
          subscriptionId: ${AZURE1_SUBSCRIPTION_ID}
          tenantId: ${AZURE1_TENANT_ID}
          clientId: ${AZURE1_CLIENT_ID}
          clientSecret: ${AZURE1_CLIENT_SECRET}
        - name: AZURE_SUBSCRIPTION2
          subscriptionId: ${AZURE2_SUBSCRIPTION_ID}
          tenantId: ${AZURE2_TENANT_ID}
          clientId: ${AZURE2_CLIENT_ID}
          clientSecret: ${AZURE2_CLIENT_SECRET}
        - name: AZURE_SUBSCRIPTION3
          subscriptionId: ${AZURE3_SUBSCRIPTION_ID}
          tenantId: ${AZURE3_TENANT_ID}
          clientId: ${AZURE3_CLIENT_ID}
          clientSecret: ${AZURE3_CLIENT_SECRET}
```

When I go to DevTools, tab 'config' there is json format listing app-config.yaml configuration, and there first AZURE_SUBSCRIPTION1 has hidden secrets but others are visible.

```json
"infraWallet":{1 item
"integrations":{2 items
"azure":[12 items
0:{5 items
"name":string"AZURE_SUBSCRIPTION1"
"subscriptionId":string"XXXXXXXXXX"
"tenantId":string"YYYYYYYYYYYY"
"clientId":ZZZZZZZZZZZZ"
"clientSecret":string"<secret>" // here is fine
}
1:{5 items
"name":string"AZURE_SUBSCRIPTION2"
"subscriptionId":string"XXXXXXXXXX"
"tenantId":string"YYYYYYYYYYYY"
"clientId":ZZZZZZZZZZZZ"
"clientSecret":string"exposed_secret" // not okay
}
2:{5 items
"name":string"AZURE_SUBSCRIPTION3"
"subscriptionId":string"XXXXXXXXXX"
"tenantId":string"YYYYYYYYYYYY"
"clientId":ZZZZZZZZZZZZ"
"clientSecret":string"exposed_secret" // not okay
}
```

And also there is warning for InfraWallet in DevTools in tab 'config':

Warning: Config validation failed:
- Config must NOT have more than 1 items { limit=1 } at /backend/infraWallet/integrations/azure

Warning is okay but I am wondering how can I hide other secrets like AZURE_SUBSCRIPTION2, AZURE_SUBSCRIPTION3.

Thanks
