### ISSUE TITLE
Support for GCP Cloud Billing 

### ISSUE THREAD

**Issue by nia-potato** [electrolux-oss/infrawallet#4]
Hi thanks for the great plugin, 

Was wondering if we can later add support GCP cloud billing, and since GCP is project based, can we separately add a tab in the entity details page, so that we can view each relavant gcp project costs? 

I know this may be a big ask, please let me know if theres any way i can help.

**Comment by gluckzhang** [comment]
Hi @nia-potato, thank you for your suggestion :)

Of course, supporting GCP costs has been listed on our roadmap and we do welcome the community to contribute. We have not started working on this one yet. So if you have time, welcome to take a look at this part https://github.com/electrolux-oss/infrawallet#how-to-support-a-new-cloud-vendor.

The first version could be in the config file, where there is a set of Google project credentials like the following:

```
  infraWallet:
    integrations:
      gcp:
        - name: the-name-of-this-google-project
          # ... necessary credentials
          tags: ["team:a", "environment:test"]
```

Then you can check the costs grouped by either the name of projects or by some custom tags. What do you think?
