### ISSUE TITLE
Cloud Provider Support: MongoAtlas

### ISSUE THREAD

**Issue by gluckzhang** [electrolux-oss/infrawallet#57]

**Comment by holiiveira** [comment]
I've done some simple testing on this in the past, it's a cloud provider we use, we can work together.

**Comment by gluckzhang** [comment]
Hi @holiiveira , that's great to hear! Sure, we can work together on this one :)

We also have used MongoAtlas billing APIs in another platform: https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Invoices/operation/listInvoices This API returns invoices in the CSV format and then we iterate all the rows and transform the cost data into our required format. I think we can also use this way in our `MongoAtlasClient` here. Though downloading several CSVs and transforming the data may take more time, I guess it will still be acceptable.

For end users, the approach above is easier with respect to onboarding because only an API key is required. Another way to get the cost information from MongoAtlas is to set up a billing dashboard: https://www.mongodb.com/docs/charts/dashboards/manage-dashboards/billing-dashboards/ I have not tried this one yet and am not sure if we can get cost data from the dashboard via an API. It also requires more configurations in order to use it.

What do you think? Which way do you prefer?

**Comment by holiiveira** [comment]
Hi @gluckzhang, my tests were exactly on this API, and we do exactly as you mentioned. I think it's better to use API, precisely because it's easier to integrate for end users. I see some scenarios:

- Cost per organization
- Cost per organization and project
- Cost per organization, project and cluster

Thinking about my use case, here we have an organization, where we have several projects (squads) that in turn have their clusters. Still in my use case, if the cost is only per organization, I would use Azure, since our billing is through there (marketplace).

Maybe have a dynamic configuration, to suit these use cases, example:

- Cost per organization
```yaml
infraWallet:
  integrations:
    mongoatlas:
      - orgName:
        orgID:
        publicKey:
        privateKey:
```

- Cost per organization and project
```yaml
infraWallet:
  integrations:
    mongoatlas:
      - projectName:
        orgName:
        orgID:
        publicKey:
        privateKey:
```

- Cost per organization, project and cluster
```yaml
infraWallet:
  integrations:
    mongoatlas:
      - clusterName:
        projectName:
        orgName:
        orgID:
        publicKey:
        privateKey:

```

What do you think about this? Does this make sense?
