### ISSUE TITLE
Config Error when running this on GKE cluster 

### ISSUE THREAD

**Issue by nia-potato** [electrolux-oss/infrawallet#92]
```
/app/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/dist/index.cjs.js:704
            throw new errors.ForwardedError(
                  ^

ForwardedError: Plugin 'app' startup failed; caused by Error: Invalid app bundle schema. If this error is unexpected you need to run `yarn build` in the app. If that doesn't help you should make sure your config schema is correct and rebuild the app bundle again. Caused by the following schema error, Error: Config validation failed, Config must have required property 'infraWallet' { missingProperty=infraWallet } at 
    at /app/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/dist/index.cjs.js:704:19
    at async /app/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/dist/index.cjs.js:703:11
    ... 3 lines matching cause stack trace ...
    at async BackstageBackend.start (/app/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/dist/index.cjs.js:867:5) {
  cause: Error: Invalid app bundle schema. If this error is unexpected you need to run `yarn build` in the app. If that doesn't help you should make sure your config schema is correct and rebuild the app bundle again. Caused by the following schema error, Error: Config validation failed, Config must have required property 'infraWallet' { missingProperty=infraWallet } at 
```

hi @gluckzhang  i think this might be a misconfiguration that i cant catch somewhere, if you can take a look that will be great. 

As i was trying to add infrawallet to our live cluster. i am getting this config error. 

My current config 

i created the secret
```
 kubectl create secret generic gcp-key-secret --from-file=test.json   -n backstage
 ```

i am doing the app deployments via helm as you can see the live appconfig defined in the helm chart, as opposed the app-config during build
```
  extraVolumeMounts:
    - mountPath: /gcp-key-secret
      name: gcp-key-secret
  extraVolumes:
    - name: gcp-key-secret
      secret:
        defaultMode: 420
        secretName: gcp-key-secret


  appConfig:
    app:
      title: Test
      baseUrl: https://test
    organization:
      name: test
      backend:
        listen:
          port: 7007
        host: test.test.team
        auth:
          keys:
            - secret:
        infraWallet:
          integrations:
            gcp:
              - name: gcp-data
                keyFilePath: /gcp-key-secret/key.json
                projectId: projectID
                datasetId: billing
                tableId: billing
        csp:
        database:
        cache:
```

Things i've checked:

- I dont think this is an secret value issue, since i have verified that my secret is accessible by directly going into the Erroring container for the first few seconds, and running a cat against the absolute path i've set, i can cat the json key properly. 
-  the secret is in the correct namespace as the application 
-  i verified the live configmap + deployment is what i defined as above. 
- the gcp billing parameters are all correct, since i was able to resolve it locally. 
- I add a dummy block during build so that it can build correct for the local app-config.yaml + app-config.production.yaml

```
  infraWallet:
    integrations:
      gcp:
        - name: gcp
          keyFilePath: /test.json
          projectId:bq
          datasetId: bill
          tableId: gcp_sample_export
 ```

Does anything look off to you based on my current config?

**Comment by gluckzhang** [comment]
Hi @nia-potato thanks for reporting this issue. I think this might be related to our default settings for frontend (which should be optional by design). Could you please try adding the following configurations to your app-config.yaml file?

```yaml
infraWallet:
  settings:
    defaultShowLastXMonths: 3
```

Feel free to adjust the values or add other options documented [here](https://github.com/electrolux-oss/infrawallet/blob/main/docs/getting-started.md#default-settings-for-frontend).

Also note that `infraWallet` is put at the root level of the yaml file (you already have `backend.infraWallet` there but this is another one for frontend).
